---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: document
  path: content/menu/menu.json
  label: Menysida
- type: document
  path: content/data/info.json
  label: Infosida
- type: directory
  path: content/pages
  label: Övriga sidor
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - page
- type: heading
  label: Sidinställningar
- type: document
  path: config.json
  label: Information
upload_dir: content/images
public_path: "/content/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv/public"
  instant_preview_command: npm run forestry-preview
